wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/llama/gmm.py
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.43.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723116498.645383
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 13
      - 23
      4: 3.10.13
      5: 0.16.1
      6: 4.43.3
      8:
      - 5
      13: linux-x86_64
